apiVersion : apps/v1
kind: Deployment
metadata:
  name: k8sapplication 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sapplication
  template:
    metadata:
      labels:
        app: k8sapplication 
    spec:
      containers:
        - name: k8sapplication 
          image: myacr2020.azurecr.io/k8sapplication
          ports:
          - containerPort: 8888